require "RGItem"

class 'RGItemManager'

function RGItemManager:__init()
	self:CreateItem()
end

function RGItemManager:CreateItem()
	local item = RGItem()
	local anim = item:CreateAnimation("flog")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/flog_01.png")
	anim:AddFrame("images/ITEM/flog_02.png")
	anim:AddFrame("images/ITEM/flog_03.png")
	anim:AddFrame("images/ITEM/flog_04.png")

	local anim = item:CreateAnimation("jinseng")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/jinseng_01.png")
	anim:AddFrame("images/ITEM/jinseng_02.png")
	anim:AddFrame("images/ITEM/jinseng_03.png")
	anim:AddFrame("images/ITEM/jinseng_04.png")

	local anim = item:CreateAnimation("potion")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/potion_01.png")
	anim:AddFrame("images/ITEM/potion_02.png")
	anim:AddFrame("images/ITEM/potion_03.png")
	anim:AddFrame("images/ITEM/potion_04.png")

	local anim = item:CreateAnimation("sword")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/sword_01.png")
	anim:AddFrame("images/ITEM/sword_02.png")
	anim:AddFrame("images/ITEM/sword_03.png")
	anim:AddFrame("images/ITEM/sword_04.png")

	local anim = item:CreateAnimation("dragonpen")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/dragonpen_01.png")
	anim:AddFrame("images/ITEM/dragonpen_02.png")
	anim:AddFrame("images/ITEM/dragonpen_03.png")
	anim:AddFrame("images/ITEM/dragonpen_04.png")

	local anim = item:CreateAnimation("sunglass")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/sunglass_01.png")
	anim:AddFrame("images/ITEM/sunglass_02.png")
	anim:AddFrame("images/ITEM/sunglass_03.png")
	anim:AddFrame("images/ITEM/sunglass_04.png")

	local anim = item:CreateAnimation("shield")
	anim:SetLoop(true)
	anim:SetDelay(0.25)
	anim:SetOffset(0,0)
	anim:AddFrame("images/ITEM/shield_01.png")
	anim:AddFrame("images/ITEM/shield_02.png")
	anim:AddFrame("images/ITEM/shield_03.png")
	anim:AddFrame("images/ITEM/shield_04.png")
end